name: Swift

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Build
        run: swift build -v
